allowBuilds:
  '@firebase/util': true
  aws-sdk: true
  bcrypt: true
  msgpackr-extract: true
  protobufjs: true
  puppeteer: true
onlyBuiltDependencies:
  - '@firebase/util'
  - aws-sdk
  - bcrypt
  - msgpackr-extract
  - protobufjs
  - puppeteer
