apiVersion: v1
kind: ConfigMap
metadata:
  name: dayf-backend-config
  namespace: dayf-booking
  labels:
    app.kubernetes.io/name: dayf-backend
    app.kubernetes.io/part-of: dayf-booking
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  IP: "0.0.0.0"
  PORT: "8000"
  SOCKET_PORT: "8005"
  REDIS_HOST: "dayf-redis"
  REDIS_PORT: "6379"
