apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dayf-backend
  namespace: dayf-booking
  labels:
    app.kubernetes.io/name: dayf-backend
    app.kubernetes.io/part-of: dayf-booking
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "dayf-route"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "10800"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "None"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.techcrafters.tech
        - socket.techcrafters.tech
      secretName: dayf-booking-tls
  rules:
    - host: api.techcrafters.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dayf-backend
                port:
                  name: http
    - host: socket.techcrafters.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dayf-backend
                port:
                  name: socket
