apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dayf-redis-ingress
  namespace: dayf-booking
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: dayf-redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: dayf-backend
      ports:
        - protocol: TCP
          port: 6379
